name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.3.2+2
  path_provider: ^1.6.18
  image: ^2.0.7
  google_fonts: ^1.1.0
  dropdown_formfield: ^0.1.3
  flutter_share: ^1.0.2+1
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.13
  search_map_place: ^0.3.0
  firebase_messaging: ^6.0.16
  firebase_core:
  firebase_analytics:



  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.jpg"


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/logo.jpg



